### ISSUE TITLE
Reblogs allow recursive reblogs

### ISSUE THREAD

**Issue by bwoff11** [bwoff11/frens#3]
**Describe the bug**
Currently, sites like Twitter allow you to retweet, but once a retweet has been made you cannot retweet your own retweet.

**Expected behavior**
- Status requests containing reblogs made by the requesting user should return with: Reblogged - True
- Status requests containing reblogs made by another user should return with: Reblogged - False

**Comment by Autoclitic** [comment]
Could you possibly make it so when a user reblog/likes an item, it has a record of said item in a like history? That way you can compare records and either gray they button out (reblog) or give them the ability to unlike the item.

**Comment by bwoff11** [comment]
> Could you possibly make it so when a user reblog/likes an item, it has a record of said item in a like history? 
The current state (aka interaction) of a user and status is currently tracked. So lets say you go a like a status, then an object will be created in the DB showing that you did that. Same for blocking, muting notifications, etc.

https://github.com/bwoff11/frens/blob/development/internal/db/interaction.go

This object is actually never returned to the user directly, IIRC, but its used quite frequently to generate some of the fields on the status object, such as the number of reblogs. I just have to add the logic to make sure it is returning reblogged: true when the requesting user has already reblogged it and false when its another.
